
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/specification
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  logging:
    level:
      org:
        hibernate:
          type: trace
  redis:
    host: localhost
    password:
    port: 8080
    lettuce:
      shutdown: 30000
      pool:
        max-active: 30
        max-idle: 10
        min-idle: 10